// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flrenxfoixmxwhctdfnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscmVueGZvaXhteHdoY3RkZm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTgyODIsImV4cCI6MjA1OTE5NDI4Mn0.sjYUclDcRbZx2Dg_tPJoy7DKklYR9J08JQRgYTAgp_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);